# Generated by Django 5.0.3 on 2024-05-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddoapp', '0002_remove_trip_location_remove_trip_transportation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='start_date_time',
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meddoapp.place')),
            ],
        ),
    ]
